# Generated by Django 3.2.8 on 2021-10-17 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0003_delete_stockwatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_threshold', models.FloatField()),
                ('lower_threshold', models.FloatField()),
                ('interval', models.CharField(choices=[('5d', '5d'), ('60m', '60m'), ('3mo', '3mo'), ('2m', '2m'), ('1d', '1d'), ('1wk', '1wk'), ('1mo', '1mo'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('90m', '90m'), ('1m', '1m'), ('5m', '5m')], default='1d', max_length=5)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watcher',
                'verbose_name_plural': 'Watcher',
            },
        ),
    ]
