# Generated by Django 3.2.8 on 2021-10-17 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_delete_stockwatch'),
        ('watchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcher',
            name='interval',
            field=models.CharField(choices=[('60m', '60m'), ('15m', '15m'), ('3mo', '3mo'), ('5m', '5m'), ('2m', '2m'), ('30m', '30m'), ('1m', '1m'), ('90m', '90m'), ('1h', '1h'), ('1wk', '1wk'), ('1d', '1d'), ('1mo', '1mo'), ('5d', '5d')], default='1d', max_length=5, verbose_name='Intervalo'),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='lower_threshold',
            field=models.FloatField(verbose_name='Limite inferior'),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='upper_threshold',
            field=models.FloatField(verbose_name='Limite superior'),
        ),
    ]
