# Generated by Django 3.2.8 on 2021-10-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0002_auto_20211017_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcher',
            name='interval',
            field=models.CharField(choices=[('1mo', '1mo'), ('2m', '2m'), ('15m', '15m'), ('5m', '5m'), ('90m', '90m'), ('1d', '1d'), ('5d', '5d'), ('1m', '1m'), ('1wk', '1wk'), ('1h', '1h'), ('3mo', '3mo'), ('30m', '30m'), ('60m', '60m')], default='1d', max_length=5, verbose_name='Intervalo'),
        ),
    ]
