# Generated by Django 3.2.8 on 2021-10-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0004_auto_20211021_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcher',
            name='interval',
            field=models.CharField(choices=[('30m', '30m'), ('60m', '60m'), ('1m', '1m'), ('1h', '1h'), ('5d', '5d'), ('1wk', '1wk'), ('1mo', '1mo'), ('2m', '2m'), ('1d', '1d'), ('3mo', '3mo'), ('5m', '5m'), ('90m', '90m'), ('15m', '15m')], default='1d', max_length=5, verbose_name='Intervalo'),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='schedule_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
