# Generated by Django 3.2.8 on 2021-10-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0010_alter_watcher_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcher',
            name='interval',
            field=models.CharField(choices=[('2m', '2m'), ('1d', '1d'), ('5d', '5d'), ('5m', '5m'), ('30m', '30m'), ('15m', '15m'), ('90m', '90m'), ('1wk', '1wk'), ('1mo', '1mo'), ('1h', '1h'), ('3mo', '3mo'), ('60m', '60m'), ('1m', '1m')], default='1d', max_length=5, verbose_name='Intervalo'),
        ),
    ]
