# Generated by Django 3.2.8 on 2021-10-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0011_alter_watcher_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watcher',
            old_name='schedule',
            new_name='schedule_id',
        ),
        migrations.AlterField(
            model_name='watcher',
            name='interval',
            field=models.CharField(choices=[('15m', '15m'), ('1mo', '1mo'), ('5m', '5m'), ('1d', '1d'), ('3mo', '3mo'), ('90m', '90m'), ('60m', '60m'), ('2m', '2m'), ('1h', '1h'), ('5d', '5d'), ('1wk', '1wk'), ('1m', '1m'), ('30m', '30m')], default='1d', max_length=5, verbose_name='Intervalo'),
        ),
    ]
