# Generated by Django 3.2.8 on 2021-10-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0012_auto_20211024_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watcher',
            options={'verbose_name': 'Watcher', 'verbose_name_plural': 'Watchers'},
        ),
        migrations.AlterField(
            model_name='watcher',
            name='interval',
            field=models.CharField(choices=[('1m', '1m'), ('1h', '1h'), ('1wk', '1wk'), ('5m', '5m'), ('90m', '90m'), ('5d', '5d'), ('1mo', '1mo'), ('30m', '30m'), ('1d', '1d'), ('3mo', '3mo'), ('2m', '2m'), ('15m', '15m'), ('60m', '60m')], default='1d', max_length=5, verbose_name='Intervalo'),
        ),
    ]
