# Generated by Django 3.2.8 on 2021-10-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0013_auto_20211024_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcher',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='interval',
            field=models.CharField(choices=[('1wk', '1 semana'), ('15m', '15 minutos'), ('60m', '60 minutos'), ('1h', '1 hora'), ('5d', '5 dias'), ('30m', '30 minutos'), ('1m', '1 minuto'), ('2m', '2 minutos'), ('1mo', '1 mês'), ('5m', '5 minutos'), ('1d', '1 dia'), ('3mo', '3 meses'), ('90m', '90 minutos')], default='1d', max_length=5, verbose_name='Intervalo'),
        ),
    ]
