# Generated by Django 3.2.8 on 2021-10-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockwatch',
            name='interval',
            field=models.CharField(choices=[('5m', '5m'), ('30m', '30m'), ('1mo', '1mo'), ('1h', '1h'), ('1d', '1d'), ('3mo', '3mo'), ('2m', '2m'), ('15m', '15m'), ('5d', '5d'), ('1m', '1m'), ('1wk', '1wk'), ('90m', '90m'), ('60m', '60m')], default='1d', max_length=5),
        ),
    ]
